# Generated by Django 5.2.13 on 2026-04-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_city_geography'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hotel',
            new_name='hotels_hote_city_id_09ce11_idx',
            old_name='hotels_hote_city_id_2c8b1f_idx',
        ),
    ]
