# Generated by Django 5.2.13 on 2026-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_hotels_hote_city_id_2c8b1f_idx_hotels_hote_city_id_09ce11_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='oyo_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Original OYO property id when imported from CSV.', null=True, unique=True),
        ),
    ]
