# Generated by Django 5.2.13 on 2026-04-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotelimage_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon displayed on the UI.', max_length=10)),
                ('category', models.CharField(blank=True, help_text='Grouping label, e.g. "Connectivity", "Food".', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='hotels.amenity'),
        ),
    ]
