# Generated by Django 5.2.13 on 2026-04-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_seed_india_cities'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='city',
            new_name='locations_c_name_5719ba_idx',
            old_name='locations_ci_name_7267cc_idx',
        ),
    ]
